-- 코드를 입력하세요
SELECT pr.PRODUCT_CODE, SUM(pr.PRICE * os.SALES_AMOUNT) as SALES
FROM PRODUCT pr
JOIN OFFLINE_SALE os ON pr.PRODUCT_ID = os.PRODUCT_ID
GROUP BY pr.PRODUCT_CODE
ORDER BY SALES DESC, pr.PRODUCT_CODE
