-- 코드를 입력하세요
SELECT aout.ANIMAL_ID, aout.NAME
FROM ANIMAL_OUTS aout
LEFT JOIN ANIMAL_INS ains
ON ains.ANIMAL_ID = aout.ANIMAL_ID
WHERE ains.DATETIME > aout.DATETIME
GROUP BY aout.NAME
ORDER BY ains.DATETIME ASC