-- 코드를 입력하세요
SELECT bk.BOOK_ID, ath.AUTHOR_NAME, DATE_FORMAT(bk.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK bk
LEFT JOIN AUTHOR ath
ON bk.AUTHOR_ID = ath.AUTHOR_ID
WHERE bk.CATEGORY='경제'
ORDER BY bk.PUBLISHED_DATE ASC